/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'Project' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* ARM::RTOS&FreeRTOS:Config&FreeRTOS@10.5.1 */
#define RTE_RTOS_FreeRTOS_CONFIG        /* RTOS FreeRTOS Config for FreeRTOS API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@10.5.1 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Coroutines@10.5.1 */
#define RTE_RTOS_FreeRTOS_COROUTINE     /* RTOS FreeRTOS Co-routines */
/* ARM::RTOS&FreeRTOS:Event Groups@10.5.1 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@10.5.1 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Message Buffer@10.5.1 */
#define RTE_RTOS_FreeRTOS_MESSAGE_BUFFER /* RTOS FreeRTOS Message Buffers */
/* ARM::RTOS&FreeRTOS:Stream Buffer@10.5.1 */
#define RTE_RTOS_FreeRTOS_STREAM_BUFFER /* RTOS FreeRTOS Stream Buffers */
/* ARM::RTOS&FreeRTOS:Timers@10.5.1 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* Keil::Device:StdPeriph Drivers:BKP@3.6.0 */
#define RTE_DEVICE_STDPERIPH_BKP
/* Keil::Device:StdPeriph Drivers:DBGMCU@3.6.0 */
#define RTE_DEVICE_STDPERIPH_DBGMCU
/* Keil::Device:StdPeriph Drivers:EXTI@3.6.0 */
#define RTE_DEVICE_STDPERIPH_EXTI
/* Keil::Device:StdPeriph Drivers:Flash@3.6.0 */
#define RTE_DEVICE_STDPERIPH_FLASH
/* Keil::Device:StdPeriph Drivers:Framework@3.6.0 */
#define RTE_DEVICE_STDPERIPH_FRAMEWORK
/* Keil::Device:StdPeriph Drivers:GPIO@3.6.0 */
#define RTE_DEVICE_STDPERIPH_GPIO
/* Keil::Device:StdPeriph Drivers:IWDG@3.6.0 */
#define RTE_DEVICE_STDPERIPH_IWDG
/* Keil::Device:StdPeriph Drivers:PWR@3.6.0 */
#define RTE_DEVICE_STDPERIPH_PWR
/* Keil::Device:StdPeriph Drivers:RCC@3.6.0 */
#define RTE_DEVICE_STDPERIPH_RCC
/* Keil::Device:StdPeriph Drivers:RTC@3.6.0 */
#define RTE_DEVICE_STDPERIPH_RTC
/* Keil::Device:StdPeriph Drivers:SPI@3.6.0 */
#define RTE_DEVICE_STDPERIPH_SPI
/* Keil::Device:StdPeriph Drivers:TIM@3.6.0 */
#define RTE_DEVICE_STDPERIPH_TIM
/* Keil::Device:StdPeriph Drivers:USART@3.6.0 */
#define RTE_DEVICE_STDPERIPH_USART


#endif /* RTE_COMPONENTS_H */
